Bookstore: styling
aradradev/bookstore pull request #6
Opened 2023-07-20 13:23 UTC by aradradev

In this pull request, I implemented the following features:

- Add any missing JSX elements to the project (without adding extra functionality)
- The final design should match zeplin's design (this includes all elements + the same styling)

Please review this pull request and any feedback on how I could enhance it is truly appreciated.

2023-07-20 15:53 UTC, Strangeal requested changes
Hi @aradradev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjBkMDI3OWJlYzRhNWVlNmIyZmE5NjU5NzFlZTA0NDVjZWFhMmQ2NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Correct **Semantics** used ✅ 
- Well-structured project ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 15:53 UTC, Strangeal commented on src/index.css
> +  padding: 0.9rem;
- [ ] Great job on adding style to your project as mentioned in the project requirements! 👏 However, your styling doesn't match the original design, and due to that it doesn't adhere to some parts of the project requirements which state that 👇👇
<img width="731" alt="Screenshot 2023-07-20 at 15 38 20" src="https://github.com/aradradev/bookstore/assets/107192076/086e4fd7-175d-4d36-b2f3-557ad4b69bde">


<hr />

`Note:` **Your styles should match exactly that of the `zeplin` design. Including `font-(color, size, weight)`, `background`, `buttons`, `input`, `spacing`, `layout`, etc. You're not to personalize any part of the design.** 


<table>
<tr>
<th align=“middle”>Replin design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="703" alt="Screenshot 2023-07-20 at 15 47 28" src="https://github.com/aradradev/bookstore/assets/107192076/11c85cc2-1c12-4242-ae3a-ced985be5eca">
</td>
<td>
<img width="1296" alt="Screenshot 2023-07-20 at 15 47 48" src="https://github.com/aradradev/bookstore/assets/107192076/d92f9a9b-af80-4009-8a33-5509267e4b73">
</td>
</tr>
</table>

2023-07-20 18:36 UTC, algerina requested changes
Hi @aradradev ,

Great job so far! 

May I highlight the following: 
- [x] You have a descriptive PR and commit history👏  ✔️ 
- [x] Your design look almost like the Zeplin design✔️ 




## CHANGES REQUIRED:muscle::clap:
Check the comments under the review.

<img src="https://media4.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>
 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-07-20 18:36 UTC, algerina commented on src/index.css
>  @media screen and (min-width: 800px) {
- [ ] Well done working on the style however you still have some details to work on:
- Kindly use the same font and color as the Zeplin design .

Your design:

<img width="1703" alt="Screenshot 2023-07-20 at 7 28 34 PM" src="https://github.com/aradradev/bookstore/assets/53347966/19ed3351-175e-4d74-98f5-54ecf923364d">

2023-07-21 09:12 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @aradradev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 Great job making changes as requested by previous reviewers.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 09:23 UTC, merged